### ISSUE TITLE
No route registered for '/websitelogs/'

### ISSUE THREAD

**Issue by MrCsabaToth** [amitapl/ThatLogExtension#10]
After installation of the extension when I try to navigate to https://myappname.scm.azurewebsites.net/websitelogs/ I get that message. What/where should I configure?

**Comment by amitapl** [comment]
Did you try to restart the website?

**Comment by MrCsabaToth** [comment]
No sir, I'll. I wrote custom error handlers for both MVC and API controller which deliver an email to per exception at this moment.

**Comment by MrCsabaToth** [comment]
That helped, thanks.

**Comment by amitapl** [comment]
:+1:

**Comment by rjgmail88** [comment]
I am having similar issue after configuring Log browser for nodejs bot I have hosted on azure app service.  Any thoughts ?
